apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam:::role/EksWorkshopCodeBuildKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::131804891577:role/eksctl-reinvent2022-east-2-nodegr-NodeInstanceRole-ZD1OBXKHPMKV
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-14T04:15:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1645"
  uid: cadee062-35ce-4b56-a2a4-7a9414abfa26
