apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::131804891577:role/EksWorkshopCodeBuildKubectlRole
      username: build
      groups:
        - system:masters
    - rolearn: arn:aws:iam::131804891577:role/EKS-reinvent-dop319-worker-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::131804891577:role/terraform-20221120020827929500000003
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::131804891577:role/EKS-reinvent-dop319-worker-node-role\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-11-20T01:41:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "16784"
  uid: 076b06e3-7a0c-4387-bed8-adcfdb235243
